openapi: 3.0.3
info:
  title: FGN.Academy Credential API
  version: 1.0.0
  description: |
    Credential management API for the FGN ecosystem.
    Enables external apps to issue, verify, and query skill credentials.
    
    ## Authentication
    
    The API supports three authentication methods:
    - **None**: Public endpoints for viewing passports and verifying credentials
    - **Bearer Token**: JWT from Supabase Auth for user's own credentials
    - **API Key**: X-App-Key header for authorized external applications
    
  contact:
    name: FGN Academy Support
    url: https://fgn.academy/developers
  license:
    name: Proprietary
    url: https://fgn.academy/terms

servers:
  - url: https://vfzjfkcwromssjnlrhoo.supabase.co/functions/v1/credential-api
    description: Production

tags:
  - name: Public
    description: No authentication required
  - name: Authenticated
    description: Requires user JWT token
  - name: Authorized Apps
    description: Requires API key from registered app

paths:
  /passport/{slug}:
    get:
      summary: Get public passport
      description: Retrieve a user's public skill passport by URL slug
      operationId: getPassport
      tags: [Public]
      parameters:
        - name: slug
          in: path
          required: true
          description: Public URL slug of the passport
          schema:
            type: string
          example: john-doe-cdl
        - name: game
          in: query
          description: Filter credentials by game title
          schema:
            type: string
            enum: [ATS, Farming_Sim, Construction_Sim, Mechanic_Sim]
          example: ATS
      responses:
        '200':
          description: Passport with credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PassportResponse'
        '404':
          description: Passport not found or not public
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /credentials/verify:
    post:
      summary: Verify a credential
      description: Verify the authenticity of a credential using its verification hash
      operationId: verifyCredential
      tags: [Public]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyRequest'
      responses:
        '200':
          description: Verification result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResponse'
        '400':
          description: Missing verification_hash
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Credential not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResponse'

  /catalog/credential-types:
    get:
      summary: List credential types
      description: Get all active credential types available in the system
      operationId: listCredentialTypes
      tags: [Public]
      parameters:
        - name: game
          in: query
          description: Filter by game title
          schema:
            type: string
            enum: [ATS, Farming_Sim, Construction_Sim, Mechanic_Sim]
      responses:
        '200':
          description: List of credential types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialTypesResponse'

  /credentials/mine:
    get:
      summary: Get my credentials
      description: Retrieve all credentials for the authenticated user
      operationId: getMyCredentials
      tags: [Authenticated]
      security:
        - BearerAuth: []
      parameters:
        - name: game
          in: query
          description: Filter by game title
          schema:
            type: string
            enum: [ATS, Farming_Sim, Construction_Sim, Mechanic_Sim]
      responses:
        '200':
          description: User's credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialsResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /credentials/issue:
    post:
      summary: Issue a credential
      description: Issue a new credential to a user (authorized apps only)
      operationId: issueCredential
      tags: [Authorized Apps]
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueRequest'
      responses:
        '201':
          description: Credential issued successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueResponse'
        '400':
          description: Invalid credential type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /credentials/user/{email}:
    get:
      summary: Get user credentials
      description: Retrieve credentials for a specific user by email (authorized apps only)
      operationId: getUserCredentials
      tags: [Authorized Apps]
      security:
        - ApiKeyAuth: []
      parameters:
        - name: email
          in: path
          required: true
          description: URL-encoded user email/username
          schema:
            type: string
          example: trainee%40example.com
        - name: game
          in: query
          description: Filter by game title
          schema:
            type: string
            enum: [ATS, Farming_Sim, Construction_Sim, Mechanic_Sim]
      responses:
        '200':
          description: User's credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialsResponse'
        '401':
          description: Invalid API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: App does not have read permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-App-Key
      description: API key for authorized external applications
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase JWT token from user session

  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Not found
      required:
        - error

    Credential:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          example: Pre-Trip Inspection Certification
        credential_type:
          type: string
          example: certification
        credential_type_key:
          type: string
          example: ats_pre_trip
        game_title:
          type: string
          enum: [ATS, Farming_Sim, Construction_Sim, Mechanic_Sim]
        issued_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
          nullable: true
        score:
          type: number
          example: 95
          nullable: true
        issuer:
          type: string
          example: cdl-quest
        skills_verified:
          type: array
          items:
            type: string
          example: [pre_trip_inspection, vehicle_safety]
        verification_hash:
          type: string
          example: a1b2c3d4e5f6...

    User:
      type: object
      properties:
        username:
          type: string
          example: john-doe
        avatar_url:
          type: string
          format: uri
          nullable: true
        employability_score:
          type: number
          example: 85
          nullable: true

    PassportResponse:
      type: object
      properties:
        passport:
          type: object
          properties:
            slug:
              type: string
              example: john-doe-cdl
            user:
              $ref: '#/components/schemas/User'
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/Credential'

    VerifyRequest:
      type: object
      properties:
        verification_hash:
          type: string
          description: SHA-256 hash from the credential
          example: a1b2c3d4e5f6789...
      required:
        - verification_hash

    VerifyResponse:
      type: object
      properties:
        valid:
          type: boolean
        expired:
          type: boolean
        credential:
          allOf:
            - $ref: '#/components/schemas/Credential'
            - type: object
              properties:
                holder_username:
                  type: string
                  example: john-doe

    CredentialType:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type_key:
          type: string
          example: ats_pre_trip
        display_name:
          type: string
          example: Pre-Trip Inspection Certification
        description:
          type: string
          nullable: true
        game_title:
          type: string
          enum: [ATS, Farming_Sim, Construction_Sim, Mechanic_Sim]
          nullable: true
        icon_name:
          type: string
          example: clipboard-check
        accent_color:
          type: string
          example: "#3B82F6"
        skills_granted:
          type: array
          items:
            type: string
        issuer_app_slug:
          type: string
          nullable: true
        sort_order:
          type: integer

    CredentialTypesResponse:
      type: object
      properties:
        credential_types:
          type: array
          items:
            $ref: '#/components/schemas/CredentialType'

    CredentialsResponse:
      type: object
      properties:
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/Credential'

    IssueRequest:
      type: object
      properties:
        user_email:
          type: string
          description: Email/username of the target user
          example: trainee@example.com
        credential_type_key:
          type: string
          description: Credential type to issue
          example: ats_pre_trip
        score:
          type: number
          description: Score achieved (0-100)
          example: 95
        skills_verified:
          type: array
          description: Skills to record (defaults to credential type's skills)
          items:
            type: string
          example: [pre_trip_inspection, defensive_driving]
        external_reference_id:
          type: string
          description: Your app's reference ID for linking
          example: session_12345
      required:
        - user_email
        - credential_type_key

    IssueResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        credential:
          $ref: '#/components/schemas/Credential'
        verification_url:
          type: string
          format: uri
          example: https://vfzjfkcwromssjnlrhoo.supabase.co/functions/v1/credential-api/credentials/verify

    UserCredentialsResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/Credential'
