// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in FGN Academy user's profile (username, display name, XP, tenant).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-my-work-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient2(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_work_orders_default = defineTool2({
  name: "list_my_work_orders",
  title: "List my work orders",
  description: "List work orders visible to the signed-in FGN Academy user (respects tenant and RLS).",
  inputSchema: {
    limit: z.number().int().positive().max(100).optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("work_orders").select("id, title, generated_name, game_title, difficulty, is_active, xp_reward, created_at, tenant_id").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = (data ?? []).map((wo) => ({
      ...wo,
      status: wo.is_active ? "active" : "inactive"
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { work_orders: rows }
    };
  }
});

// src/lib/mcp/tools/list-my-communities.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser3(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient3(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_communities_default = defineTool3({
  name: "list_my_communities",
  title: "List my communities",
  description: "List the communities (tenants) the signed-in FGN Academy user is a member of.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("community_memberships").select("role, joined_at, tenant:tenants(id, name, slug, logo_url, accent_color, brand_color)").eq("user_id", ctx.getUserId()).eq("request_status", "approved");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const memberships = (data ?? []).filter((r) => r.tenant).map((r) => ({
      tenant_id: r.tenant.id,
      name: r.tenant.name,
      slug: r.tenant.slug,
      logo_url: r.tenant.logo_url,
      accent_color: r.tenant.accent_color,
      brand_color: r.tenant.brand_color,
      role: r.role
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(memberships) }],
      structuredContent: { memberships }
    };
  }
});

// src/lib/mcp/tools/list-tenants.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient4(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tenants_default = defineTool4({
  name: "list_tenants",
  title: "List tenants",
  description: "List tenants (communities) visible to the signed-in user under RLS.",
  inputSchema: {
    limit: z2.number().int().positive().max(100).optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("tenants").select("id, name, slug, logo_url, accent_color, brand_color, description, is_verified").order("name", { ascending: true }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tenants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-games.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient5(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_games_default = defineTool5({
  name: "list_games",
  title: "List games",
  description: "List the games catalog. On this project the catalog is keyed by the game_title enum (returned as `id`); there is no separate games table with UUID ids.",
  inputSchema: {
    limit: z3.number().int().positive().max(100).optional().describe("Max rows to return (default 50, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.from("game_channels").select("game_title, name, description, accent_color, cover_image_url, member_count, work_order_count").order("name", { ascending: true }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const games = (data ?? []).map((g) => ({
      id: g.game_title,
      name: g.name,
      description: g.description,
      accent_color: g.accent_color,
      cover_image_url: g.cover_image_url,
      member_count: g.member_count,
      work_order_count: g.work_order_count
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(games) }],
      structuredContent: { games }
    };
  }
});

// src/lib/mcp/tools/list-challenges.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient6(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_challenges_default = defineTool6({
  name: "list_challenges",
  title: "List challenges",
  description: "List challenges (work_orders) visible to the caller under RLS. Filter by game_title (enum string, e.g. 'Fiber_Tech'), tenant_id, or is_active.",
  inputSchema: {
    game_title: z4.string().optional().describe("Game enum name (e.g. 'Fiber_Tech'). This project has no separate games UUID."),
    tenant_id: z4.string().uuid().optional(),
    is_active: z4.boolean().optional(),
    limit: z4.number().int().positive().max(100).optional().describe("Max rows (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ game_title, tenant_id, is_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser6(ctx);
    let q = supabase.from("work_orders").select("id, title, generated_name, game_title, is_active, difficulty, xp_reward, tenant_id, fgn_origin_challenge_id, source_challenge_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (game_title !== void 0) q = q.eq("game_title", game_title);
    if (tenant_id !== void 0) q = q.eq("tenant_id", tenant_id);
    if (is_active !== void 0) q = q.eq("is_active", is_active);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { challenges: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-challenge.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient7(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_challenge_default = defineTool7({
  name: "get_challenge",
  title: "Get challenge",
  description: "Return a single challenge (work_orders row) with its child tasks (work_order_tasks). RLS-scoped.",
  inputSchema: {
    id: z5.string().uuid().describe("Challenge (work_order) UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser7(ctx);
    const [challengeRes, tasksRes] = await Promise.all([
      supabase.from("work_orders").select("*").eq("id", id).maybeSingle(),
      supabase.from("work_order_tasks").select("id, title, description, order_index, source_task_id").eq("work_order_id", id).order("order_index", { ascending: true })
    ]);
    if (challengeRes.error) {
      return { content: [{ type: "text", text: challengeRes.error.message }], isError: true };
    }
    if (tasksRes.error) {
      return { content: [{ type: "text", text: tasksRes.error.message }], isError: true };
    }
    const payload = { challenge: challengeRes.data, tasks: tasksRes.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-passport.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z6 } from "npm:zod@^3.25.76";
function supabaseForUser8(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient8(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_passport_default = defineTool8({
  name: "get_passport",
  title: "Get passport",
  description: "Return a user's skill passport: profile, passport record, earned credentials, badges, and career readiness (only for users the caller can read under RLS).",
  inputSchema: {
    user_id: z6.string().uuid().optional().describe("Target user. Defaults to the signed-in caller. Other users only returned when RLS permits.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ user_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const targetUserId = user_id ?? ctx.getUserId();
    const supabase = supabaseForUser8(ctx);
    const { data: profile, error: profileErr } = await supabase.from("profiles").select("id, username, avatar_url, employability_score, skills, tenant_id, created_at, updated_at").eq("id", targetUserId).maybeSingle();
    if (profileErr) {
      return { content: [{ type: "text", text: profileErr.message }], isError: true };
    }
    if (!profile) {
      const empty = { profile: null, passport: null, credentials: [], badges: [], readiness: null };
      return {
        content: [{ type: "text", text: JSON.stringify(empty) }],
        structuredContent: empty
      };
    }
    const [passportRes, badgesRes] = await Promise.all([
      supabase.from("skill_passport").select("id, passport_hash, public_url_slug, is_public, created_at, updated_at").eq("user_id", targetUserId).maybeSingle(),
      supabase.from("user_badges").select("earned_at, badge:badges(id, name, description, icon_name, game_title, category, accent_color)").eq("user_id", targetUserId)
    ]);
    let credentials = [];
    if (passportRes.data?.id) {
      const { data: creds } = await supabase.from("skill_credentials").select("id, credential_type, credential_type_key, title, issuer, issued_at, expires_at, skills_verified, score, game_title, xp_earned, source").eq("passport_id", passportRes.data.id).order("issued_at", { ascending: false });
      credentials = creds ?? [];
    }
    const { data: readiness } = await supabase.rpc("calculate_readiness", { p_user_id: targetUserId });
    const payload = {
      profile,
      passport: passportRes.data ?? null,
      credentials,
      badges: badgesRes.data ?? [],
      readiness: readiness ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-sim-categories.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z7 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.93.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser9(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient9(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-sim-categories.ts
var list_sim_categories_default = defineTool9({
  name: "list_sim_categories",
  title: "List SIM categories",
  description: "List the industry categories (sim_categories) that group SIM games on FGN Academy. These drive the Work Orders filters and the sidebar.",
  inputSchema: {
    include_inactive: z7.boolean().optional().describe("Include categories marked inactive.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_inactive }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser9(ctx);
    let q = supabase.from("sim_categories").select(
      "id, key, title, subtitle, icon_key, accent_color, default_game_titles, display_order, is_active, sidebar_label, show_in_sidebar"
    ).order("display_order", { ascending: true });
    if (!include_inactive) q = q.eq("is_active", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-community.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z8 } from "npm:zod@^3.25.76";
var CATEGORY_TYPES = [
  "geography",
  "broadband_provider",
  "trade_skill",
  "school",
  "employer",
  "training_center",
  "government",
  "nonprofit",
  "community_organization",
  "club",
  "cte"
];
var create_community_default = defineTool10({
  name: "create_community",
  title: "Create community",
  description: "Create a new community (tenant) on FGN Academy. Runs as the signed-in user, so it only succeeds for admins permitted to create communities.",
  inputSchema: {
    name: z8.string().trim().min(2).describe("Display name of the community."),
    slug: z8.string().trim().regex(/^[a-z0-9-]+$/, "Lowercase letters, numbers and hyphens only.").describe("URL slug, e.g. 'north-valley-cte'."),
    description: z8.string().trim().optional(),
    category_type: z8.enum(CATEGORY_TYPES).optional(),
    brand_color: z8.string().trim().optional().describe("Hex color, e.g. '#F59E0B'."),
    website_url: z8.string().url().optional(),
    parent_tenant_id: z8.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser9(ctx);
    const { data, error } = await supabase.from("tenants").insert({ ...input, owner_id: ctx.getUserId() }).select("id, name, slug, approval_status, category_type, parent_tenant_id").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { community: data }
    };
  }
});

// src/lib/mcp/tools/update-community.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z9 } from "npm:zod@^3.25.76";
var update_community_default = defineTool11({
  name: "update_community",
  title: "Update community",
  description: "Update an existing community (tenant): name, description, branding, contact URLs or industries. Only fields you pass are changed. RLS restricts this to admins of that community.",
  inputSchema: {
    id: z9.string().uuid().describe("Community (tenant) UUID."),
    name: z9.string().trim().min(2).optional(),
    description: z9.string().trim().optional(),
    tagline: z9.string().trim().optional(),
    brand_color: z9.string().trim().optional(),
    accent_color: z9.string().trim().optional(),
    logo_url: z9.string().url().optional(),
    cover_image_url: z9.string().url().optional(),
    website_url: z9.string().url().optional(),
    support_email: z9.string().email().optional(),
    location: z9.string().trim().optional(),
    industries: z9.array(z9.string()).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const fields = Object.fromEntries(
      Object.entries(patch).filter(([, v]) => v !== void 0)
    );
    if (Object.keys(fields).length === 0) {
      return { content: [{ type: "text", text: "No fields to update" }], isError: true };
    }
    const supabase = supabaseForUser9(ctx);
    const { data, error } = await supabase.from("tenants").update(fields).eq("id", id).select("id, name, slug, description, brand_color, industries").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Community not found or not editable by this user." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { community: data }
    };
  }
});

// src/lib/mcp/tools/upsert-sim-category.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z10 } from "npm:zod@^3.25.76";
var GAME_TITLES = [
  "ATS",
  "Farming_Sim",
  "Construction_Sim",
  "Mechanic_Sim",
  "Fiber_Tech",
  "Roadcraft",
  "MSFS_2024",
  "House_Flipper",
  "House_Flipper_2",
  "Electrician_Sim"
];
var upsert_sim_category_default = defineTool12({
  name: "upsert_sim_category",
  title: "Create or update SIM category",
  description: "Create or update an industry category (sim_categories) by its unique `key`. Categories name the Work Orders filters and the sidebar entries, and map to one or more SIM games.",
  inputSchema: {
    key: z10.string().trim().min(2).describe("Stable unique key, e.g. 'trucking-logistics'."),
    title: z10.string().trim().min(2).describe("Industry filter name, e.g. 'Trucking & Logistics'."),
    subtitle: z10.string().trim().optional(),
    icon_key: z10.string().trim().optional().describe("Icon key from the app's SIM icon set."),
    accent_color: z10.string().trim().optional().describe("Hex color, e.g. '#F59E0B'."),
    default_game_titles: z10.array(z10.enum(GAME_TITLES)).optional().describe("SIM games in this industry."),
    display_order: z10.number().int().min(0).optional(),
    is_active: z10.boolean().optional(),
    sidebar_label: z10.string().trim().optional().describe("Sidebar label when it differs from the filter name."),
    show_in_sidebar: z10.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const row = Object.fromEntries(Object.entries(input).filter(([, v]) => v !== void 0));
    const supabase = supabaseForUser9(ctx);
    const { data, error } = await supabase.from("sim_categories").upsert(row, { onConflict: "key" }).select(
      "id, key, title, subtitle, icon_key, accent_color, default_game_titles, display_order, is_active, sidebar_label, show_in_sidebar"
    ).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { category: data }
    };
  }
});

// src/lib/mcp/tools/upsert-work-order.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z11 } from "npm:zod@^3.25.76";
var GAME_TITLES2 = [
  "ATS",
  "Farming_Sim",
  "Construction_Sim",
  "Mechanic_Sim",
  "Fiber_Tech",
  "Roadcraft",
  "MSFS_2024",
  "House_Flipper",
  "House_Flipper_2",
  "Electrician_Sim"
];
var upsert_work_order_default = defineTool13({
  name: "upsert_work_order",
  title: "Create or update work order",
  description: "Create a work order (challenge), or update one when `id` is supplied. `game_title` is required on create. Runs as the signed-in user, so RLS restricts writes to admins of the owning community.",
  inputSchema: {
    id: z11.string().uuid().optional().describe("Work order UUID. Omit to create a new one."),
    title: z11.string().trim().min(2).optional(),
    description: z11.string().trim().optional(),
    game_title: z11.enum(GAME_TITLES2).optional().describe("Required when creating."),
    difficulty: z11.enum(["beginner", "intermediate", "advanced"]).optional(),
    xp_reward: z11.number().int().min(0).optional(),
    estimated_time_minutes: z11.number().int().positive().optional(),
    category_key: z11.string().trim().optional().describe("Industry category key from list_sim_categories."),
    tenant_id: z11.string().uuid().optional().describe("Owning community; omit for the global catalog."),
    cover_image_url: z11.string().url().optional(),
    is_active: z11.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ id, ...input }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const fields = Object.fromEntries(Object.entries(input).filter(([, v]) => v !== void 0));
    if (Object.keys(fields).length === 0) {
      return { content: [{ type: "text", text: "Nothing to write" }], isError: true };
    }
    const supabase = supabaseForUser9(ctx);
    const selection = "id, title, description, game_title, difficulty, xp_reward, category_key, tenant_id, is_active, created_at";
    if (id) {
      const { data: data2, error: error2 } = await supabase.from("work_orders").update(fields).eq("id", id).select(selection).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!data2) {
        return {
          content: [{ type: "text", text: "Work order not found or not editable by this user." }],
          isError: true
        };
      }
      return {
        content: [{ type: "text", text: JSON.stringify(data2) }],
        structuredContent: { work_order: data2 }
      };
    }
    if (!fields.game_title) {
      return { content: [{ type: "text", text: "game_title is required when creating a work order." }], isError: true };
    }
    const { data, error } = await supabase.from("work_orders").insert(fields).select(selection).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { work_order: data }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z12 } from "npm:zod@^3.25.76";
var list_courses_default = defineTool14({
  name: "list_courses",
  title: "List courses",
  description: "List courses visible to the signed-in user under RLS. Filter by tenant_id (community) to see one community's curriculum, e.g. Acme Broadband.",
  inputSchema: {
    tenant_id: z12.string().uuid().optional().describe("Owning community UUID."),
    is_published: z12.boolean().optional(),
    limit: z12.number().int().positive().max(100).optional().describe("Max rows (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_id, is_published, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser9(ctx);
    let query = supabase.from("courses").select(
      "id, title, description, game_title, difficulty_level, xp_reward, is_published, visibility, tenant_id, owner_tenant_id, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (tenant_id) query = query.eq("tenant_id", tenant_id);
    if (is_published !== void 0) query = query.eq("is_published", is_published);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z13 } from "npm:zod@^3.25.76";
var get_course_default = defineTool15({
  name: "get_course",
  title: "Get course",
  description: "Return one course with its modules and lessons (including quiz question counts). RLS-scoped to the signed-in user.",
  inputSchema: { id: z13.string().uuid().describe("Course UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser9(ctx);
    const { data: course, error } = await supabase.from("courses").select(
      "id, title, description, game_title, difficulty_level, xp_reward, is_published, visibility, tenant_id, owner_tenant_id"
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!course) return { content: [{ type: "text", text: "Course not found" }], isError: true };
    const { data: modules } = await supabase.from("modules").select("id, title, description, order_index, xp_reward").eq("course_id", id).order("order_index");
    const moduleIds = (modules ?? []).map((m) => m.id);
    const { data: lessons } = moduleIds.length ? await supabase.from("lessons").select("id, module_id, title, lesson_type, order_index, xp_reward, passing_score, work_order_id, content").in("module_id", moduleIds).order("order_index") : { data: [] };
    const shaped = (modules ?? []).map((m) => ({
      ...m,
      lessons: (lessons ?? []).filter((l) => l.module_id === m.id).map((l) => ({
        ...l,
        question_count: Array.isArray(l.content?.questions) ? l.content.questions.length : 0
      }))
    }));
    const payload = { course, modules: shaped };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/upsert-course.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z14 } from "npm:zod@^3.25.76";
var GAME_TITLES3 = [
  "ATS",
  "Farming_Sim",
  "Construction_Sim",
  "Mechanic_Sim",
  "Fiber_Tech",
  "Roadcraft",
  "MSFS_2024",
  "House_Flipper",
  "House_Flipper_2",
  "Electrician_Sim"
];
var upsert_course_default = defineTool16({
  name: "upsert_course",
  title: "Create or update course",
  description: "Create a course for a community (pass tenant_id, e.g. Acme Broadband), or update one when `id` is supplied. Runs as the signed-in user, so RLS restricts writes to admins of the owning community.",
  inputSchema: {
    id: z14.string().uuid().optional().describe("Course UUID. Omit to create."),
    title: z14.string().trim().min(2).optional(),
    description: z14.string().trim().optional(),
    game_title: z14.enum(GAME_TITLES3).optional(),
    difficulty_level: z14.enum(["beginner", "intermediate", "advanced"]).optional(),
    xp_reward: z14.number().int().min(0).optional(),
    cover_image_url: z14.string().url().optional(),
    tenant_id: z14.string().uuid().optional().describe("Owning community; required when creating a community course."),
    visibility: z14.enum(["public", "tenant", "private"]).optional(),
    is_published: z14.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ id, ...input }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const fields = Object.fromEntries(
      Object.entries(input).filter(([, v]) => v !== void 0)
    );
    if (Object.keys(fields).length === 0) {
      return { content: [{ type: "text", text: "Nothing to write" }], isError: true };
    }
    if (fields.tenant_id && !fields.owner_tenant_id) fields.owner_tenant_id = fields.tenant_id;
    const supabase = supabaseForUser9(ctx);
    const selection = "id, title, description, game_title, difficulty_level, xp_reward, is_published, visibility, tenant_id, owner_tenant_id";
    if (id) {
      const { data: data2, error: error2 } = await supabase.from("courses").update(fields).eq("id", id).select(selection).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!data2) {
        return {
          content: [{ type: "text", text: "Course not found or not editable by this user." }],
          isError: true
        };
      }
      return { content: [{ type: "text", text: JSON.stringify(data2) }], structuredContent: { course: data2 } };
    }
    if (!fields.title) {
      return { content: [{ type: "text", text: "title is required when creating a course." }], isError: true };
    }
    const { data, error } = await supabase.from("courses").insert(fields).select(selection).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { course: data } };
  }
});

// src/lib/mcp/tools/upsert-lesson.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z15 } from "npm:zod@^3.25.76";
var questionSchema = z15.object({
  id: z15.string().trim().min(1).optional().describe("Stable question id; generated when omitted."),
  prompt: z15.string().trim().min(2),
  options: z15.array(z15.string().trim().min(1)).min(2).max(8),
  correct_index: z15.number().int().min(0).describe("Zero-based index of the correct option."),
  explanation: z15.string().trim().optional()
});
var upsert_lesson_default = defineTool17({
  name: "upsert_lesson",
  title: "Create or update lesson or quiz",
  description: "Create a lesson (or quiz) inside a course, or update one when `id` is supplied. Each lesson gets its own module, matching the platform's 1:1 curriculum structure. For quizzes pass `lesson_type: 'quiz'` and `questions`. Runs as the signed-in user, so RLS restricts writes to admins of the owning community.",
  inputSchema: {
    id: z15.string().uuid().optional().describe("Lesson UUID. Omit to create."),
    course_id: z15.string().uuid().optional().describe("Course to add the lesson to. Required when creating."),
    title: z15.string().trim().min(2).optional(),
    lesson_type: z15.enum(["video", "reading", "quiz", "simulation", "work_order"]).optional(),
    xp_reward: z15.number().int().min(0).optional(),
    passing_score: z15.number().int().min(0).max(100).optional().describe("Percent needed to pass a quiz."),
    order_index: z15.number().int().min(0).optional(),
    work_order_id: z15.string().uuid().optional().describe("Link the lesson to a work order (challenge)."),
    frame: z15.string().trim().optional().describe("Framing text shown before the activity."),
    play: z15.string().trim().optional().describe("Instructions for the hands-on step."),
    prove: z15.string().trim().optional().describe("What the learner must demonstrate."),
    questions: z15.array(questionSchema).optional().describe("Quiz questions; replaces existing questions.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ id, course_id, frame, play, prove, questions, ...input }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser9(ctx);
    const selection = "id, module_id, title, lesson_type, order_index, xp_reward, passing_score, work_order_id, content";
    const buildContent = (existing) => {
      const content2 = { ...existing ?? {} };
      if (frame !== void 0) content2.frame = frame;
      if (play !== void 0) content2.play = play;
      if (prove !== void 0) content2.prove = prove;
      if (frame !== void 0 || play !== void 0 || prove !== void 0) content2.tier = "light";
      if (questions !== void 0) {
        content2.questions = questions.map((q, i) => ({
          id: q.id ?? `q${i + 1}`,
          prompt: q.prompt,
          options: q.options,
          correct_index: q.correct_index,
          ...q.explanation ? { explanation: q.explanation } : {}
        }));
      }
      return Object.keys(content2).length ? content2 : null;
    };
    const fields = Object.fromEntries(
      Object.entries(input).filter(([, v]) => v !== void 0)
    );
    if (id) {
      const { data: existing, error: readErr } = await supabase.from("lessons").select("content").eq("id", id).maybeSingle();
      if (readErr) return { content: [{ type: "text", text: readErr.message }], isError: true };
      if (!existing) {
        return { content: [{ type: "text", text: "Lesson not found or not visible to this user." }], isError: true };
      }
      const content2 = buildContent(existing.content);
      if (content2) fields.content = content2;
      if (Object.keys(fields).length === 0) {
        return { content: [{ type: "text", text: "Nothing to write" }], isError: true };
      }
      const { data: data2, error: error2 } = await supabase.from("lessons").update(fields).eq("id", id).select(selection).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!data2) {
        return { content: [{ type: "text", text: "Lesson not editable by this user." }], isError: true };
      }
      return { content: [{ type: "text", text: JSON.stringify(data2) }], structuredContent: { lesson: data2 } };
    }
    if (!course_id || !fields.title) {
      return {
        content: [{ type: "text", text: "course_id and title are required when creating a lesson." }],
        isError: true
      };
    }
    const { count } = await supabase.from("modules").select("id", { count: "exact", head: true }).eq("course_id", course_id);
    const orderIndex = fields.order_index ?? count ?? 0;
    const { data: moduleRow, error: moduleErr } = await supabase.from("modules").insert({
      course_id,
      title: fields.title,
      order_index: orderIndex,
      xp_reward: fields.xp_reward ?? 0
    }).select("id").maybeSingle();
    if (moduleErr) return { content: [{ type: "text", text: moduleErr.message }], isError: true };
    if (!moduleRow) {
      return {
        content: [{ type: "text", text: "Could not create the module for this lesson (check admin permissions)." }],
        isError: true
      };
    }
    const content = buildContent(null);
    const { data, error } = await supabase.from("lessons").insert({
      ...fields,
      module_id: moduleRow.id,
      order_index: 0,
      ...content ? { content } : {}
    }).select(selection).maybeSingle();
    if (error) {
      await supabase.from("modules").delete().eq("id", moduleRow.id);
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { lesson: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vfzjfkcwromssjnlrhoo";
var mcp_default = defineMcp({
  name: "fgn-academy-mcp",
  title: "FGN Academy",
  version: "0.4.0",
  instructions: "Tools for the FGN Academy workforce training platform. Read the signed-in user's profile, work orders, community memberships, tenants, games catalog, industry SIM categories, challenges, courses and skill passport \u2014 and, for admins, create or update communities, SIM categories, work orders, courses, lessons and quizzes for a specific community. All calls run as the authenticated user under row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_my_communities_default,
    list_my_work_orders_default,
    list_tenants_default,
    list_games_default,
    list_challenges_default,
    get_challenge_default,
    get_passport_default,
    list_sim_categories_default,
    list_courses_default,
    get_course_default,
    create_community_default,
    update_community_default,
    upsert_sim_category_default,
    upsert_work_order_default,
    upsert_course_default,
    upsert_lesson_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
