create table public.scorm_courses (
  id uuid primary key default gen_random_uuid(),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  destination text not null check (destination in (
    'fgn-academy',
    'broadband-workforce',
    'simu-cdl-path',
    'external-lms'
  )),
  title text not null,
  description text,
  cover_image_url text,
  scorm_version text not null default '1.2'
    check (scorm_version in ('1.2', 'cmi5')),
  manifest_url text not null,
  zip_url text,
  bundle_id text not null,
  is_published boolean not null default true,
  published_at timestamptz default now(),
  generated_by uuid references auth.users(id) on delete set null,
  source_challenge_id uuid,
  ai_enhanced jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (work_order_id, destination)
);

create index scorm_courses_work_order_idx
  on public.scorm_courses(work_order_id);

create index scorm_courses_published_idx
  on public.scorm_courses(is_published)
  where is_published;

create trigger scorm_courses_updated_at
before update on public.scorm_courses
for each row execute function public.update_updated_at_column();

alter table public.scorm_courses enable row level security;

create policy "anyone can read published scorm courses"
on public.scorm_courses
for select
to public
using (is_published = true);

create policy "admins can read all scorm courses"
on public.scorm_courses
for select
to authenticated
using (
  has_role(auth.uid(), 'admin'::app_role)
  or has_role(auth.uid(), 'super_admin'::app_role)
);

create policy "admins can manage scorm courses"
on public.scorm_courses
for all
to authenticated
using (
  has_role(auth.uid(), 'admin'::app_role)
  or has_role(auth.uid(), 'super_admin'::app_role)
)
with check (
  has_role(auth.uid(), 'admin'::app_role)
  or has_role(auth.uid(), 'super_admin'::app_role)
);

comment on table public.scorm_courses is
  'SCORM 1.2 courses generated by the Course Builder admin UI from fgn.academy Work Orders. One row per (Work Order, destination); regenerate replaces in place.';

comment on column public.scorm_courses.destination is
  'Distribution path: fgn-academy renders as a Learning Resource card on the source Work Order page; the other three are admin-downloads-ZIP destinations.';

comment on column public.scorm_courses.manifest_url is
  'Public URL to the unzipped course.json under media-assets/scorm-courses/<id>/.';

comment on column public.scorm_courses.zip_url is
  'Public URL to the full SCORM ZIP under media-assets/scorm-bundles/<id>.zip.';

comment on column public.scorm_courses.ai_enhanced is
  'Mirror of CourseManifest.aiEnhanced when AI slots ran during build.';